GET http://localhost:3000/student/marks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtpcmEiLCJ1c2VySWQiOjE1LCJpYXQiOjE2NTg0MjIxMTEsImV4cCI6MTY1ODQyNTcxMX0.Jmr4_jTBq6-DvCMC_Prin5GXYmlXsyAqtGuEQFQ4Uts

###
POST http://localhost:3000/student/marks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtpcmEiLCJ1c2VySWQiOjE1LCJpYXQiOjE2NTg0MTkwMjksImV4cCI6MTY1ODQyMjYyOX0.AMgU611a5myZ38cNjgCmlEmg8e_I2kTKVX1cx_rGNuA

{
    "maxMarks": 100,
    "marks": 100,
    "year": "2022",
    "subjectId": 12
}