POST http://localhost:3000/students
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtpcmEiLCJ1c2VySWQiOjE1LCJpYXQiOjE2NTg0MTMzODEsImV4cCI6MTY1ODQxNjk4MX0.Q1sJsjMMadEX2SXIiqlHWwg21ldrrREhFmKS6AbdTm0

{
    "name": "Raj",
    "gender": "M",
    "dob":"16/12/1999",
    "enrollmentNo":"12345"
}

###

GET http://localhost:3000/students
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtpcmEiLCJ1c2VySWQiOjE1LCJpYXQiOjE2NTg0MTY3MzAsImV4cCI6MTY1ODQyMDMzMH0.Zi3ygPQBSkEEcutXcqFFQ3FkLw5Fe-WXTFjBL9s7QTQ

###

GET http://localhost:3000/students/8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtpcmEiLCJ1c2VySWQiOjE1LCJpYXQiOjE2NTg0MTY3MzAsImV4cCI6MTY1ODQyMDMzMH0.Zi3ygPQBSkEEcutXcqFFQ3FkLw5Fe-WXTFjBL9s7QTQ