POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "username": "rem",
    "password": "rem123"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "kira",
    "password": "kira123"
}

# raj raj123 rem rem123 kira kira123